paths:
  /api/v1/admin/article-tags:
    get:
      summary: 获取标签列表
      description: 获取文章标签列表，支持分页查询
      operationId: getArticleTagList
      security:
        - BearerAuth: []
      tags:
        - tags
      parameters:
        - name: current
          in: query
          description: 当前页码
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: 每页显示的记录数
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: 成功获取标签列表
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagListResp"
              example:
                code: 1
                msg: 获取成功！
                data:
                  total: 1
                  data:
                    - tagId: 1
                      name: 技术
                    - tagId: 2
                      name: 生活
                  current: 1
                  pageSize: 10
        "400":
          description: 请求参数错误
        "500":
          description: 服务器内部错误
  /api/v1/article-tags/{tagId}:
    delete:
      summary: 删除标签
      description: 根据标签 ID 删除指定的标签
      operationId: deleteTag
      security:
        - BearerAuth: []
      tags:
        - tags
      parameters:
        - name: tagId
          in: path
          description: 标签 ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: 标签删除成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResp"
              example:
                code: 1
                msg: 删除成功！
                data:
                  tagId: 1
                  name: 技术
        "404":
          description: 标签不存在
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
              example:
                code: 404
                msg: 标签不存在！
        "500":
          description: 服务器内部错误
components:
  schemas:
    TagListResp:
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              oneOf:
                - type: object
                  properties:
                    pagination:
                      $ref: "#/components/schemas/Pagination"
                    data:
                      type: array
                      description: 文章列表
                      items:
                        $ref: "#/components/schemas/ArticleTag"
                  required:
                    - pagination
                    - ArticleTag
                - type: array
                  description: 文章列表，不包含分页信息
                  items:
                    $ref: "#/components/schemas/ArticleTag"
    TagResp:
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/ArticleTag"
    ArticleTag:
      type: object
      properties:
        tagId:
          type: integer
          description: 标签ID
          example: 1
        name:
          type: string
          description: 标签名称
          example: "技术"
