swagger: "2.0"
info:
  title: MBCRM Dispatch API
  version: 1.0.0
  description: API for managing dispatch records in MBCRM system

paths:
  /api/v1/admin/dispatch/list:
    get:
      tags:
        - dispatch
      summary: Get dispatch list
      description: Returns a paginated list of dispatch records
      parameters:
        - $ref: "#/parameters/current"
        - $ref: "#/parameters/pageSize"
        - name: hospitalId
          in: query
          description: Filter by hospital ID
          required: false
          type: integer
        - name: customerId
          in: query
          description: Filter by customer ID
          required: false
          type: integer
        - name: status
          in: query
          description: Filter by status (0=待派单,1=已派单,2=已确认,3=已完成,4=已取消)
          required: false
          type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/ListResponse_Dispatch_"

  /api/v1/admin/dispatch:
    post:
      tags:
        - dispatch
      summary: Create a dispatch
      description: Creates a new dispatch record
      parameters:
        - name: body
          in: body
          description: Dispatch object that needs to be created
          required: true
          schema:
            $ref: "#/definitions/DispatchInput"
      responses:
        200:
          description: Successfully created
          schema:
            $ref: "#/definitions/Dispatch"
        400:
          description: Invalid input

  /api/v1/admin/dispatch/{dispatchId}:
    get:
      tags:
        - dispatch
      summary: Get dispatch by ID
      description: Returns a single dispatch record
      parameters:
        - name: dispatchId
          in: path
          description: ID of dispatch to return
          required: true
          type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/Dispatch"
        404:
          description: Dispatch not found

    put:
      tags:
        - dispatch
      summary: Update a dispatch
      description: Updates an existing dispatch record
      parameters:
        - name: dispatchId
          in: path
          description: ID of dispatch to update
          required: true
          type: integer
        - name: body
          in: body
          description: Dispatch object that needs to be updated
          required: true
          schema:
            $ref: "#/definitions/DispatchInput"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/Dispatch"
        400:
          description: Invalid input
        404:
          description: Dispatch not found

    delete:
      tags:
        - dispatch
      summary: Delete a dispatch
      description: Deletes a dispatch record
      parameters:
        - name: dispatchId
          in: path
          description: ID of dispatch to delete
          required: true
          type: integer
      responses:
        200:
          description: Successfully deleted
        404:
          description: Dispatch not found

definitions:
  Dispatch:
    type: object
    properties:
      dispatchId:
        type: integer
        description: Unique identifier for the dispatch
      hospitalId:
        type: integer
        description: ID of the hospital
      customerId:
        type: integer
        description: ID of the customer
      project:
        type: string
        description: Cosmetic project name
      dispatchTime:
        type: integer
        description: Unix timestamp of dispatch time
      dispatcherId:
        type: integer
        description: ID of the dispatcher
      status:
        type: integer
        description: Current status (0=待派单,1=已派单,2=已确认,3=已完成,4=已取消)
      message:
        type: string
        description: Additional notes
      createdId:
        type: integer
        description: ID of creator
      createdBy:
        type: string
        description: Name of creator
      updatedId:
        type: integer
        description: ID of updater
      updatedBy:
        type: string
        description: Name of updater
      createdAt:
        type: string
        format: date-time
        description: Creation timestamp
      updatedAt:
        type: string
        format: date-time
        description: Last update timestamp

  DispatchInput:
    type: object
    required:
      - hospitalId
      - customerId
      - project
      - dispatcherId
    properties:
      hospitalId:
        type: integer
        description: ID of the hospital
      customerId:
        type: integer
        description: ID of the customer
      project:
        type: string
        description: Cosmetic project name
      dispatchTime:
        type: integer
        description: Unix timestamp of dispatch time
      dispatcherId:
        type: integer
        description: ID of the dispatcher
      status:
        type: integer
        description: Current status (0=待派单,1=已派单,2=已确认,3=已完成,4=已取消)
      message:
        type: string
        description: Additional notes

  ListResponse_Dispatch_:
    type: object
    properties:
      total:
        type: integer
        description: Total number of records
      data:
        type: array
        items:
          $ref: "#/definitions/Dispatch"
      current:
        type: integer
        description: Current page number
      pageSize:
        type: integer
        description: Number of records per page

parameters:
  current:
    name: current
    in: query
    description: Current page number
    required: false
    type: integer
    default: 1
  pageSize:
    name: pageSize
    in: query
    description: Number of records per page
    required: false
    type: integer
    default: 10
