components:
  schemas:
    Response:
      type: object
      required:
        - code
        - msg
      properties:
        code:
          type: integer
          description: Response code
          example: 1
        msg:
          type: string
          description: Response message
    
    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: 当前页码
          example: 1
        pageSize:
          type: integer
          description: 每页显示的数据条数
          example: 10
        total:
          type: integer
          description: 总数据条数
          example: 2
    
    UnAuthorized:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
          description: Response message
          example: 用户身份已过期
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
tags:
  - name: users
    description: 用户相关
  - name: admins
    description: 管理员管理
  - name: roles
    description: 角色管理
  - name: menus
    description: 菜单管理
  - name: apis
    description: 接口管理
  - name: options
    description: 系统设置
  - name: medias
    description: 媒体资源
  - name: media-categories
    description: 媒体分类
  - name: depts
    description: 部门管理
  - name: posts
    description: 岗位管理
  - name: login-logs
    description: 登录日志管理
  - name: dicts
    description: 字典管理
  - name: dicts-data
    description: 字典数据
  - name: operation-logs
    description: 操作日志

  - name: article-categories
    description: 文章分类
  - name: articles
    description: 文章管理
  - name: tags
    description: 标签管理

  - name: hospital
    description: 医院管理
  - name: customer
    description: 客户管理
  - name: dispatch
    description: 派单管理


servers:
  - url: /
    description: Local server
