components:
  schemas:
    Response:
      type: object
      required:
        - code
        - msg
      properties:
        code:
          type: integer
          description: Response code
          example: 1
        msg:
          type: string
          description: Response message
    
    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: 当前页码
          example: 1
        pageSize:
          type: integer
          description: 每页显示的数据条数
          example: 10
        total:
          type: integer
          description: 总数据条数
          example: 2
    
    UnAuthorized:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
          description: Response message
          example: 用户身份已过期
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
tags:
  - name: users
    description: 用户相关
  - name: admins
    description: 管理员管理
  - name: roles
    description: 角色管理
  - name: menus
    description: 菜单管理
  - name: apis
    description: 接口管理
  - name: options
    description: 系统设置
  - name: medias
    description: 媒体资源
servers:
  - url: /
    description: Local server
