name: Deploy to ZeroCMF-Koa

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 添加根据APP_ENV生成.env文件的步骤
      - name: Generate .env file
        run: echo "${{ secrets.APP_ENV }}" > .env

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Run deploy script
        run: node scripts/deploy.js

      - name: Compress dist folder
        run: tar -czf dist.tar.gz -C ./dist .

      - name: Upload via API
        env:
          DEPLOY_NAME: ${{ secrets.DEPLOY_NAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Write private key to a temporary file
          echo "$PRIVATE_KEY" > private_key.pem

          # Upload the compressed file using curl
          curl -X POST http://deploy.zerocmf.com/api/upload \
            -F "name=$DEPLOY_NAME" \
            -F "privateKey=@private_key.pem" \
            -F "file=@dist.tar.gz" \
            -F "path=$DEPLOY_PATH" \
            -F "type=node"
            

      - name: Clean up private key file
        run: rm -f private_key.pem
