paths:
  /api/v1/admin/operation-logs:
    get:
      tags:
        - operation-logs
      summary: 获取操作日志列表
      description: 分页获取操作日志列表
      operationId: getOperationLogList
      parameters:
        - name: current
          in: query
          description: 当前页码
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: 每页记录数
          schema:
            type: integer
            default: 10
        - name: title
          in: query
          description: 模块标题
          schema:
            type: string
        - name: operName
          in: query
          description: 操作人员
          schema:
            type: string
        - name: businessType
          in: query
          description: 业务类型（0其它 1新增 2修改 3删除 4授权 5导出 6导入 7强退 8清空数据）
          schema:
            type: integer
            enum: [0, 1, 2, 3, 4, 5, 6, 7, 8]
        - name: status
          in: query
          description: 操作状态（0异常 1正常）
          schema:
            type: integer
            enum: [0, 1]
        - name: operIp
          in: query
          description: 操作IP地址
          schema:
            type: string
        - name: startTime
          in: query
          description: 开始时间（时间戳）
          schema:
            type: integer
        - name: endTime
          in: query
          description: 结束时间（时间戳）
          schema:
            type: integer
      responses:
        '200':
          description: 成功获取操作日志列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 1
                  msg:
                    type: string
                    example: 获取操作日志列表成功
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/OperationLog'
                      total:
                        type: integer
                        example: 100
                      current:
                        type: integer
                        example: 1
                      pageSize:
                        type: integer
                        example: 10
    delete:
      tags:
        - operation-logs
      summary: 删除操作日志
      description: 批量删除操作日志
      operationId: removeOperationLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
      responses:
        '200':
          description: 成功删除操作日志
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 1
                  msg:
                    type: string
                    example: 删除操作日志成功
                  data:
                    type: object

  /api/v1/admin/operation-logs/{id}:
    get:
      tags:
        - operation-logs
      summary: 获取操作日志详情
      description: 根据ID获取操作日志详情
      operationId: getOperationLogDetail
      parameters:
        - name: id
          in: path
          required: true
          description: 操作日志ID
          schema:
            type: integer
      responses:
        '200':
          description: 成功获取操作日志详情
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 1
                  msg:
                    type: string
                    example: 获取操作日志详情成功
                  data:
                    $ref: '#/components/schemas/OperationLog'

  /api/v1/admin/operation-logs/clean:
    delete:
      tags:
        - operation-logs
      summary: 清空操作日志
      description: 清空所有操作日志
      operationId: cleanOperationLog
      responses:
        '200':
          description: 成功清空操作日志
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 1
                  msg:
                    type: string
                    example: 清空操作日志成功
                  data:
                    type: object

  /api/v1/admin/operation-logs/export:
    get:
      tags:
        - operation-logs
      summary: 导出操作日志
      description: 导出操作日志数据
      operationId: exportOperationLog
      parameters:
        - name: title
          in: query
          description: 模块标题
          schema:
            type: string
        - name: operName
          in: query
          description: 操作人员
          schema:
            type: string
        - name: businessType
          in: query
          description: 业务类型（0其它 1新增 2修改 3删除 4授权 5导出 6导入 7强退 8清空数据）
          schema:
            type: integer
            enum: [0, 1, 2, 3, 4, 5, 6, 7, 8]
        - name: status
          in: query
          description: 操作状态（0异常 1正常）
          schema:
            type: integer
            enum: [0, 1]
        - name: operIp
          in: query
          description: 操作IP地址
          schema:
            type: string
        - name: startTime
          in: query
          description: 开始时间（时间戳）
          schema:
            type: integer
        - name: endTime
          in: query
          description: 结束时间（时间戳）
          schema:
            type: integer
      responses:
        '200':
          description: 成功导出操作日志
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 1
                  msg:
                    type: string
                    example: 导出操作日志成功
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/OperationLog'

components:
  schemas:
    OperationLog:
      type: object
      properties:
        operId:
          type: integer
          description: 日志主键
          example: 1
        title:
          type: string
          description: 模块标题
          example: 用户管理
        businessType:
          type: integer
          description: 业务类型（0其它 1新增 2修改 3删除 4授权 5导出 6导入 7强退 8清空数据）
          example: 1
        method:
          type: string
          description: 方法名称
          example: addUser
        requestMethod:
          type: string
          description: 请求方式
          example: POST
        operatorType:
          type: integer
          description: 操作类别（0其它 1后台用户 2手机端用户）
          example: 1
        operName:
          type: string
          description: 操作人员
          example: admin
        deptName:
          type: string
          description: 部门名称
          example: 研发部门
        operUrl:
          type: string
          description: 请求URL
          example: /api/v1/admin/users
        operIp:
          type: string
          description: 主机地址
          example: 127.0.0.1
        operLocation:
          type: string
          description: 操作地点
          example: 内网IP
        operParam:
          type: string
          description: 请求参数
          example: '{"loginName":"test","password":"******"}'
        jsonResult:
          type: string
          description: 返回参数
          example: '{"code":1,"msg":"操作成功","data":{}}'
        status:
          type: integer
          description: 操作状态（0异常 1正常）
          example: 1
        errorMsg:
          type: string
          description: 错误消息
          example: ""
        operTime:
          type: integer
          description: 操作时间（时间戳）
          example: 1647321600
        userId:
          type: integer
          description: 用户ID
          example: 1
